// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StitchPrice.Infrastructure.Persistence;

#nullable disable

namespace StitchPrice.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StitchPriceDbContext))]
    partial class StitchPriceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StitchPrice.Domain.Entities.PricingBreakdownItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PricingQuoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PricingQuoteId");

                    b.ToTable("pricing_breakdown_items", (string)null);
                });

            modelBuilder.Entity("StitchPrice.Domain.Entities.PricingQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ColorCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DigitizingFee")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("FabricType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("GarmentCostPerItem")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MarkupAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PlacementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PricePerItem")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ProfitMarginPercentage")
                        .HasColumnType("numeric(7,1)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresDigitizing")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SetupFee")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StitchCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("pricing_quotes", (string)null);
                });

            modelBuilder.Entity("StitchPrice.Domain.Entities.PricingSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("BulkDiscountEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ColorComplexityFeePerColor")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultMarkupPercentage")
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("DigitizingFee")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MinimumOrderPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PricePerThousandStitches")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SetupFee")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UrgencyMultiplier")
                        .HasColumnType("numeric(7,4)");

                    b.HasKey("Id");

                    b.ToTable("pricing_settings", (string)null);
                });

            modelBuilder.Entity("StitchPrice.Domain.Entities.ProductPricingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultGarmentCost")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DefaultMarkupPercentage")
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("DifficultyMultiplier")
                        .HasColumnType("numeric(7,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductType")
                        .IsUnique();

                    b.ToTable("product_pricing_profiles", (string)null);
                });

            modelBuilder.Entity("StitchPrice.Domain.Entities.PricingBreakdownItem", b =>
                {
                    b.HasOne("StitchPrice.Domain.Entities.PricingQuote", "Quote")
                        .WithMany("BreakdownItems")
                        .HasForeignKey("PricingQuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("StitchPrice.Domain.Entities.PricingQuote", b =>
                {
                    b.Navigation("BreakdownItems");
                });
#pragma warning restore 612, 618
        }
    }
}
